### ISSUE TITLE
please tag releases!

### ISSUE THREAD

**Issue by umlaeute** [reduzent/pduino#2]
just noticed that on [deken](https://deken.puredata.info/search.html?library=pduino) there's a pduino-0.6 (uploaded *last year*), whereas in Debian there's still pduino-0.5.

As Debian maintainer of the package, I think this is mostly because there's no easy way to automatically track new upstream releases (and I really cannot watch all the packages manually).

Please tag your releases (whenever you upload to deken, consider creating a new tag on github).

**Comment by reduzent** [comment]
Your points are all valid and of course it's not feasible to manually track all developments.  There wasn't much planing when uploading my version to deken, I just thought it would be more visible when available in Deken. 

I'm not sure if there is any maintainer of the original pduino. I thought there is none and boldly put a version higher to my version. I don't mean to forcefully take over maintainership of pduino. If nobody steps forward, I'd be happy if 0.6 becomes the "official" pduino also available in Debian.

**Comment by sesselastronaut** [comment]
I can't wait to be using pduino again, been a bit byte off the grid for the last couple of years due various reasons but school's out and happy to contribute wherever I can.

**Comment by reduzent** [comment]
Hey @sesselastronaut ... I hope things are well in the black woods.

@umlaeute: I just released (and tagged!) version 0.7. I made some cosmetic changes and adapted [declare]s to modern style (-path instead of -stdpath). Since for 0.6 it was a bit diffuse which commit actually marked it, there is clearness now. And I tested it with FIRMATA from most recent Arduino IDE (1.8.13) on an Arduino Leonardo. I think this one is ready for Debian inclusion.
